version: "3.8"
services:
  app1-blue:
    image: itsmayankanand/urlqr:${TAG}
    container_name: urlqr-app1-blue
    restart: always

  app2-blue:
    image: itsmayankanand/urlqr:${TAG}
    container_name: urlqr-app2-blue
    restart: always

  app1-green:
    image: itsmayankanand/urlqr:${TAG}
    container_name: urlqr-app1-green
    restart: always

  app2-green:
    image: itsmayankanand/urlqr:${TAG}
    container_name: urlqr-app2-green
    restart: always

  nginx:
    image: nginx:alpine
    container_name: urlqr-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always


