name: CI

on:
  push:                              # run tests when you push to any branch
    branches: ["**"]
  pull_request:                      # also run tests when you open a PR
  release:
    types: [published]               # also run tests when a release is published 

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .                       # so `from app.main import app` works

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Install the code linting and formatting tool Ruff
        run: pipx install ruff
        
      - name: Lint code with Ruff
        run: ruff check . --output-format=github --target-version=py312

      - name: Check code formatting with Ruff
        run: ruff format . --diff --target-version=py312
        continue-on-error: true

      - name: Run tests
        run: pytest -v


  docker:                                         #  JOB 2: Docker build + push
    runs-on: ubuntu-latest
    needs: tests                                  # only run if tests pass
    if: github.ref == 'refs/heads/main'           # only run on main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            itsmayankanand/urlqr:latest
            itsmayankanand/urlqr:${{ github.sha }} 


  docker-release:                                #  JOB 3: Release build
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'release' && github.event.action == 'published'
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            itsmayankanand/urlqr:release-${{ github.event.release.tag_name }}
            itsmayankanand/urlqr:${{ github.event.release.tag_name }}
  
  deploy:                                        #  JOB 4: Deploy to VM
    runs-on: ubuntu-latest
    needs: docker-release
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            docker pull itsmayankanand/urlqr:release-${{ github.event.release.tag_name }}
            docker stop urlqr || true
            docker rm urlqr || true
            docker run -d --name urlqr -p 80:8000 itsmayankanand/urlqr:release-${{ github.event.release.tag_name }}
          EOF

