name: CI

on:
  push:
    branches: ["**"]                          # Run CI when code is pushed to dev branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      # Step 4: Run linting (optional)
      - name: Run linter
        run: |
          pip install ruff
          ruff check . --fix

      # Step 5: Run tests
      - name: Run tests
        run: |
          pytest -v
